// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cloudos.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const CLOUDOS_MODELS: ModelCatalog<typeof values, "cloudos"> =
	flattenModelCatalog("cloudos", values);
